<script>
  import { _ } from "../services/i18n";
  import tippy from "sveltejs-tippy";
  import * as httpFetch from "../app/fetch.js";
  import { Names } from "../store/shutters.js";
  import { McuConfig, Gmu } from "../store/mcu_config.js";
  import { onMount } from "svelte";

  onMount(() => {
    httpFetch.http_fetchByMask(httpFetch.FETCH_GMU);
  });


  $: gmu = $Gmu;
  $: root_topic = ($McuConfig["mqtt-root-topic"] || "tfmcu") + "/";
  $: mqttText = "";
  $: moduleText = "";

  $: {
    $Gmu;
    mqttText = genText_mqtt($Gmu);
  }


  function get_name(g, m) {
    const gm = g.toString() + m.toString();
    return g.toString() + (m ? m.toString() : "A") + ($Names[gm] ? " " + $Names[gm] : "");
  }


  function genText_mqtt(gmu) {
    let txt = "# Configuration for mqtt/cover generated by tronferno-mcu webapp\n"
+ "# Copy and paste it into file configuration.yaml\n"
+ "# Location on linux installation: /home/homeassistant/.homeassistant/configuration.yaml\n"
+ "# Location on HassOS: /config/configuation.yaml\n"
+ "mqtt:\n"
+ "  cover:\n";



    for(let g=1; g < gmu.length; ++g) {
      for (let m=0; m <= gmu[g]; ++m) {
        txt +=
  `    - name: "${get_name(g,m)}"\n`
+ `      command_topic: "${root_topic + g.toString()+m.toString()}/cmd"\n`
+ `      position_topic: "${root_topic + g.toString()+m.toString()}/pct_out"\n`
+ `      set_position_topic: "${root_topic + g.toString()+m.toString()}/pct"\n`
+ `      qos: 1\n`
+ `      payload_open: "up"\n`
+ `      payload_close: "down"\n`
+ `      payload_stop: "stop"\n`;
  }
    }
    return txt;
  }

</script>

<div class="main-area">
  <h4 class="text-center" use:tippy={{ content: $_("panes.hs_config.home_assistant.tt.header") }}>{$_("panes.hs_config.home_assistant.header") }</h4>

  <div>
    <button on:click={() => {navigator.clipboard.writeText(mqttText);} }>Copy configuration to clipboard</button><br>
    <textarea value={mqttText} cols={80} rows={25} disabled={true}></textarea>
  </div>

</div>