#!/bin/sh

cat <<EOF
/*
  This file was generated by write_config.sh from Kconfig.projbuild. Do not edit.
*/

#pragma once

EOF


sed  <Kconfig.projbuild -nE -e 's/config APP_(.*)$/\1/p' | xargs -n 1 ./write_config_entry.sh APP_
