#ifndef COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H_
#define COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H_

#include "fsb.h"

typedef enum {
  MSG_TYPE_NONE, MSG_TYPE_PLAIN, MSG_TYPE_PLAIN_DOUBLE, MSG_TYPE_RTC, MSG_TYPE_TIMER
} fmsg_type;



extern uint32_t fer_centralUnit;

#endif /* COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H_ */
