#ifndef COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H
#define COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H

#include <stdint.h>

typedef enum {
  MSG_TYPE_NONE, MSG_TYPE_PLAIN, MSG_TYPE_PLAIN_DOUBLE, MSG_TYPE_RTC, MSG_TYPE_TIMER
} fmsg_type;

#endif /* COMPONENTS_FERNOTRON_INCLUDE_FERNOTRON_FER_MSG_H */
