/*
  This file was generated by write_config.sh from Kconfig.projbuild. Do not edit.
*/

#pragma once

#ifdef CONFIG_APP_USE_HTTP
#define  USE_HTTP
#ifdef __cplusplus
constexpr bool use_HTTP = true;
#else
#define use_HTTP 1
#endif
#else
#define NO_USE_HTTP
#ifdef __cplusplus
constexpr bool use_HTTP = false;
#else
#define use_HTTP 0
#endif
#endif
#ifdef CONFIG_APP_USE_LAN
#define  USE_LAN
#ifdef __cplusplus
constexpr bool use_LAN = true;
#else
#define use_LAN 1
#endif
#else
#define NO_USE_LAN
#ifdef __cplusplus
constexpr bool use_LAN = false;
#else
#define use_LAN 0
#endif
#endif
#ifdef CONFIG_APP_USE_WLAN
#define  USE_WLAN
#ifdef __cplusplus
constexpr bool use_WLAN = true;
#else
#define use_WLAN 1
#endif
#else
#define NO_USE_WLAN
#ifdef __cplusplus
constexpr bool use_WLAN = false;
#else
#define use_WLAN 0
#endif
#endif
#ifdef CONFIG_APP_USE_WLAN_AP
#define  USE_WLAN_AP
#ifdef __cplusplus
constexpr bool use_WLAN_AP = true;
#else
#define use_WLAN_AP 1
#endif
#else
#define NO_USE_WLAN_AP
#ifdef __cplusplus
constexpr bool use_WLAN_AP = false;
#else
#define use_WLAN_AP 0
#endif
#endif
#ifdef CONFIG_APP_USE_NTP
#define  USE_NTP
#ifdef __cplusplus
constexpr bool use_NTP = true;
#else
#define use_NTP 1
#endif
#else
#define NO_USE_NTP
#ifdef __cplusplus
constexpr bool use_NTP = false;
#else
#define use_NTP 0
#endif
#endif
#ifdef CONFIG_APP_USE_JSON
#define  USE_JSON
#ifdef __cplusplus
constexpr bool use_JSON = true;
#else
#define use_JSON 1
#endif
#else
#define NO_USE_JSON
#ifdef __cplusplus
constexpr bool use_JSON = false;
#else
#define use_JSON 0
#endif
#endif
#ifdef CONFIG_APP_USE_MQTT
#define  USE_MQTT
#ifdef __cplusplus
constexpr bool use_MQTT = true;
#else
#define use_MQTT 1
#endif
#else
#define NO_USE_MQTT
#ifdef __cplusplus
constexpr bool use_MQTT = false;
#else
#define use_MQTT 0
#endif
#endif
#ifdef CONFIG_APP_USE_POSIX_TIME
#define  USE_POSIX_TIME
#ifdef __cplusplus
constexpr bool use_POSIX_TIME = true;
#else
#define use_POSIX_TIME 1
#endif
#else
#define NO_USE_POSIX_TIME
#ifdef __cplusplus
constexpr bool use_POSIX_TIME = false;
#else
#define use_POSIX_TIME 0
#endif
#endif
#ifdef CONFIG_APP_USE_SERIAL
#define  USE_SERIAL
#ifdef __cplusplus
constexpr bool use_SERIAL = true;
#else
#define use_SERIAL 1
#endif
#else
#define NO_USE_SERIAL
#ifdef __cplusplus
constexpr bool use_SERIAL = false;
#else
#define use_SERIAL 0
#endif
#endif
#ifdef CONFIG_APP_USE_WDG
#define  USE_WDG
#ifdef __cplusplus
constexpr bool use_WDG = true;
#else
#define use_WDG 1
#endif
#else
#define NO_USE_WDG
#ifdef __cplusplus
constexpr bool use_WDG = false;
#else
#define use_WDG 0
#endif
#endif
#ifdef CONFIG_APP_USE_FS
#define  USE_FS
#ifdef __cplusplus
constexpr bool use_FS = true;
#else
#define use_FS 1
#endif
#else
#define NO_USE_FS
#ifdef __cplusplus
constexpr bool use_FS = false;
#else
#define use_FS 0
#endif
#endif
#ifdef CONFIG_APP_USE_HTTP_CLIENT
#define  USE_HTTP_CLIENT
#ifdef __cplusplus
constexpr bool use_HTTP_CLIENT = true;
#else
#define use_HTTP_CLIENT 1
#endif
#else
#define NO_USE_HTTP_CLIENT
#ifdef __cplusplus
constexpr bool use_HTTP_CLIENT = false;
#else
#define use_HTTP_CLIENT 0
#endif
#endif
#ifdef CONFIG_APP_USE_OTA
#define  USE_OTA
#ifdef __cplusplus
constexpr bool use_OTA = true;
#else
#define use_OTA 1
#endif
#else
#define NO_USE_OTA
#ifdef __cplusplus
constexpr bool use_OTA = false;
#else
#define use_OTA 0
#endif
#endif
#ifdef CONFIG_APP_USE_STM32OTA
#define  USE_STM32OTA
#ifdef __cplusplus
constexpr bool use_STM32OTA = true;
#else
#define use_STM32OTA 1
#endif
#else
#define NO_USE_STM32OTA
#ifdef __cplusplus
constexpr bool use_STM32OTA = false;
#else
#define use_STM32OTA 0
#endif
#endif
#ifdef CONFIG_APP_USE_CUAS
#define  USE_CUAS
#ifdef __cplusplus
constexpr bool use_CUAS = true;
#else
#define use_CUAS 1
#endif
#else
#define NO_USE_CUAS
#ifdef __cplusplus
constexpr bool use_CUAS = false;
#else
#define use_CUAS 0
#endif
#endif
#ifdef CONFIG_APP_USE_TCPS
#define  USE_TCPS
#ifdef __cplusplus
constexpr bool use_TCPS = true;
#else
#define use_TCPS 1
#endif
#else
#define NO_USE_TCPS
#ifdef __cplusplus
constexpr bool use_TCPS = false;
#else
#define use_TCPS 0
#endif
#endif
#ifdef CONFIG_APP_USE_TCPS_TASK
#define  USE_TCPS_TASK
#ifdef __cplusplus
constexpr bool use_TCPS_TASK = true;
#else
#define use_TCPS_TASK 1
#endif
#else
#define NO_USE_TCPS_TASK
#ifdef __cplusplus
constexpr bool use_TCPS_TASK = false;
#else
#define use_TCPS_TASK 0
#endif
#endif
#ifdef CONFIG_APP_USE_EG
#define  USE_EG
#ifdef __cplusplus
constexpr bool use_EG = true;
#else
#define use_EG 1
#endif
#else
#define NO_USE_EG
#ifdef __cplusplus
constexpr bool use_EG = false;
#else
#define use_EG 0
#endif
#endif
#ifdef CONFIG_APP_USE_SEP
#define  USE_SEP
#ifdef __cplusplus
constexpr bool use_SEP = true;
#else
#define use_SEP 1
#endif
#else
#define NO_USE_SEP
#ifdef __cplusplus
constexpr bool use_SEP = false;
#else
#define use_SEP 0
#endif
#endif
#ifdef CONFIG_APP_USE_WS
#define  USE_WS
#ifdef __cplusplus
constexpr bool use_WS = true;
#else
#define use_WS 1
#endif
#else
#define NO_USE_WS
#ifdef __cplusplus
constexpr bool use_WS = false;
#else
#define use_WS 0
#endif
#endif
#ifdef CONFIG_APP_USE_MUTEX
#define  USE_MUTEX
#ifdef __cplusplus
constexpr bool use_MUTEX = true;
#else
#define use_MUTEX 1
#endif
#else
#define NO_USE_MUTEX
#ifdef __cplusplus
constexpr bool use_MUTEX = false;
#else
#define use_MUTEX 0
#endif
#endif
#ifdef CONFIG_APP_USE_CLI_TASK
#define  USE_CLI_TASK
#ifdef __cplusplus
constexpr bool use_CLI_TASK = true;
#else
#define use_CLI_TASK 1
#endif
#else
#define NO_USE_CLI_TASK
#ifdef __cplusplus
constexpr bool use_CLI_TASK = false;
#else
#define use_CLI_TASK 0
#endif
#endif
#ifdef CONFIG_APP_USE_NETWORK
#define  USE_NETWORK
#ifdef __cplusplus
constexpr bool use_NETWORK = true;
#else
#define use_NETWORK 1
#endif
#else
#define NO_USE_NETWORK
#ifdef __cplusplus
constexpr bool use_NETWORK = false;
#else
#define use_NETWORK 0
#endif
#endif
#ifdef CONFIG_APP_USE_AP_FALLBACK
#define  USE_AP_FALLBACK
#ifdef __cplusplus
constexpr bool use_AP_FALLBACK = true;
#else
#define use_AP_FALLBACK 1
#endif
#else
#define NO_USE_AP_FALLBACK
#ifdef __cplusplus
constexpr bool use_AP_FALLBACK = false;
#else
#define use_AP_FALLBACK 0
#endif
#endif
#ifdef CONFIG_APP_USE_CONFIG_KVS
#define  USE_CONFIG_KVS
#ifdef __cplusplus
constexpr bool use_CONFIG_KVS = true;
#else
#define use_CONFIG_KVS 1
#endif
#else
#define NO_USE_CONFIG_KVS
#ifdef __cplusplus
constexpr bool use_CONFIG_KVS = false;
#else
#define use_CONFIG_KVS 0
#endif
#endif
#ifdef CONFIG_APP_USE_ESP_GET_TIME
#define  USE_ESP_GET_TIME
#ifdef __cplusplus
constexpr bool use_ESP_GET_TIME = true;
#else
#define use_ESP_GET_TIME 1
#endif
#else
#define NO_USE_ESP_GET_TIME
#ifdef __cplusplus
constexpr bool use_ESP_GET_TIME = false;
#else
#define use_ESP_GET_TIME 0
#endif
#endif
#ifdef CONFIG_APP_USE_FER_TRANSMITTER
#define  USE_FER_TRANSMITTER
#ifdef __cplusplus
constexpr bool use_FER_TRANSMITTER = true;
#else
#define use_FER_TRANSMITTER 1
#endif
#else
#define NO_USE_FER_TRANSMITTER
#ifdef __cplusplus
constexpr bool use_FER_TRANSMITTER = false;
#else
#define use_FER_TRANSMITTER 0
#endif
#endif
#ifdef CONFIG_APP_USE_FER_RECEIVER
#define  USE_FER_RECEIVER
#ifdef __cplusplus
constexpr bool use_FER_RECEIVER = true;
#else
#define use_FER_RECEIVER 1
#endif
#else
#define NO_USE_FER_RECEIVER
#ifdef __cplusplus
constexpr bool use_FER_RECEIVER = false;
#else
#define use_FER_RECEIVER 0
#endif
#endif
#ifdef CONFIG_APP_USE_PAIRINGS
#define  USE_PAIRINGS
#ifdef __cplusplus
constexpr bool use_PAIRINGS = true;
#else
#define use_PAIRINGS 1
#endif
#else
#define NO_USE_PAIRINGS
#ifdef __cplusplus
constexpr bool use_PAIRINGS = false;
#else
#define use_PAIRINGS 0
#endif
#endif
#ifdef CONFIG_APP_USE_GPIO_PINS
#define  USE_GPIO_PINS
#ifdef __cplusplus
constexpr bool use_GPIO_PINS = true;
#else
#define use_GPIO_PINS 1
#endif
#else
#define NO_USE_GPIO_PINS
#ifdef __cplusplus
constexpr bool use_GPIO_PINS = false;
#else
#define use_GPIO_PINS 0
#endif
#endif
#ifdef CONFIG_APP_USE_TIMER_DATA_FS
#define  USE_TIMER_DATA_FS
#ifdef __cplusplus
constexpr bool use_TIMER_DATA_FS = true;
#else
#define use_TIMER_DATA_FS 1
#endif
#else
#define NO_USE_TIMER_DATA_FS
#ifdef __cplusplus
constexpr bool use_TIMER_DATA_FS = false;
#else
#define use_TIMER_DATA_FS 0
#endif
#endif
#ifdef CONFIG_APP_USE_TIMER_DATA_KVS
#define  USE_TIMER_DATA_KVS
#ifdef __cplusplus
constexpr bool use_TIMER_DATA_KVS = true;
#else
#define use_TIMER_DATA_KVS 1
#endif
#else
#define NO_USE_TIMER_DATA_KVS
#ifdef __cplusplus
constexpr bool use_TIMER_DATA_KVS = false;
#else
#define use_TIMER_DATA_KVS 0
#endif
#endif
#ifdef CONFIG_APP_USE_FREERTOS
#define  USE_FREERTOS
#ifdef __cplusplus
constexpr bool use_FREERTOS = true;
#else
#define use_FREERTOS 1
#endif
#else
#define NO_USE_FREERTOS
#ifdef __cplusplus
constexpr bool use_FREERTOS = false;
#else
#define use_FREERTOS 0
#endif
#endif
#ifdef CONFIG_APP_USE_MDR_TIME
#define  USE_MDR_TIME
#ifdef __cplusplus
constexpr bool use_MDR_TIME = true;
#else
#define use_MDR_TIME 1
#endif
#else
#define NO_USE_MDR_TIME
#ifdef __cplusplus
constexpr bool use_MDR_TIME = false;
#else
#define use_MDR_TIME 0
#endif
#endif
