/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF)  Configuration Header
 */
#pragma once
#define CONFIG_APP_USE_MQTT 1
#define CONFIG_APP_MQTT_CLIENT_ID "zb"
#define CONFIG_APP_MQTT_ROOT_TOPIC "tfmcu"
#define CONFIG_APP_USE_POSIX_TIME 1
#define CONFIG_APP_GEO_TZ "CET-1CEST-2,M3.5.0,M10.5.0"
#define CONFIG_APP_SETTINGS_PASSWORD ""
#define CONFIG_APP_FER_CENTRAL_UNIT_ID 0x801234
#define CONFIG_APP_FER_GM_USE 0x7777777
#define CONFIG_APP_WIFI_AP_SSID "tronferno"
#define CONFIG_APP_WIFI_AP_PASSWORD "tronferno"
#define CONFIG_APP_CFG_NAMESPACE "Settings"
#define CONFIG_APP_GPIO_NUMBER_OF_GPIOS 40
#define CONFIG_MAIN_LOOP_PERIOD_MS 100
#define CONFIG_NETWORK_CHECK_LOOP_PERIOD_S 15
#define CONFIG_UOUT_HAVE_COMPONENT 1
#define CONFIG_CLI_JSON_ROOT_OBJECT 1
#define CONFIG_CLI_INTERACTIVE_CONSOLE 1
#define CONFIG_APP_USE_CLI_TASK 1
#define CONFIG_CONFIG_KVS_HAVE_COMPONENT 1
#define CONFIG_APP_OTA_USE_CERT_BUNDLE 1
#define CONFIG_STM32_HAVE_COMPONENT 1
#define CONFIG_STM32_USE_COMPONENT 1
#define CONFIG_STM32_ENABLE_RESET 1
#define CONFIG_STM32_MAKE_COMPONENT_THREAD_SAFE 1
#define CONFIG_STM32_MAKE_API_THREAD_SAFE 1
#define CONFIG_STM32_UART_PARITY_DEFAULT 0
#define CONFIG_TXTIO_HAVE_COMPONENT 1
#define CONFIG_APP_UART_BAUD_RATE 115200
#define CONFIG_WEATHER_OWM_URL_STRING "http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=12345678901234567890123456789012"
#define CONFIG_NET_HTTP_SERVER_HAVE_COMPONENT 1
#define CONFIG_APP_HTTP_ENABLE 0
#define CONFIG_APP_HTTP_USER ""
#define CONFIG_APP_HTTP_PASSWORD ""
#define CONFIG_NET_HAVE_COMPONENT 1
#define CONFIG_APP_TCPS_ENABLE 1
#define CONFIG_APP_TCPS_PORT 7777
#define CONFIG_APP_TCPS_PORT_IA 0
#define CONFIG_APP_TCPS_CONNECTIONS_MAX -1
#define CONFIG_NET_MQTT_CLIENT_HAVE_COMPONENT 1
#define CONFIG_APP_MQTT_URL ""
#define CONFIG_APP_MQTT_ENABLE 0
#define CONFIG_APP_MQTT_USER ""
#define CONFIG_APP_MQTT_PASSWORD ""
#define CONFIG_UOUT_PUBLISH_IP_ADDR_AS_TXT 1
#define CONFIG_REQUIRE_ROOT_OBJECT 1
#define CONFIG_APP_USE_FER_TRANSMITTER 1
#define CONFIG_APP_USE_FER_RECEIVER 1
#define CONFIG_APP_USE_CUAS 1
#define CONFIG_APP_USE_SEP 1
#define CONFIG_APP_USE_TIMER_DATA_KVS 1
#define CONFIG_APP_USE_PAIRINGS 1
#define CONFIG_APP_USE_REPEATER 1
#define CONFIG_APP_USE_RTC_AUTO_UPD 1
