/*
 * Automatically generated file. DO NOT EDIT.
 * Espressif IoT Development Framework (ESP-IDF)  Configuration Header
 */
#pragma once
#define CONFIG_UOUT_HAVE_COMPONENT 1
#define CONFIG_CLI_JSON_ROOT_OBJECT 1
#define CONFIG_CONFIG_KVS_HAVE_COMPONENT 1
#define CONFIG_APP_CFG_NAMESPACE "Settings"
#define CONFIG_APP_OTA_USE_CERT_BUNDLE 1
#define CONFIG_NET_HTTP_SERVER_HAVE_COMPONENT 1
#define CONFIG_APP_HTTP_ENABLE 0
#define CONFIG_APP_HTTP_USER ""
#define CONFIG_APP_HTTP_PASSWORD ""
#define CONFIG_NET_HAVE_COMPONENT 1
#define CONFIG_APP_TCPS_ENABLE 1
#define CONFIG_APP_TCPS_PORT 7777
#define CONFIG_APP_TCPS_PORT_IA 0
#define CONFIG_APP_TCPS_CONNECTIONS_MAX -1
#define CONFIG_NET_MQTT_CLIENT_HAVE_COMPONENT 1
#define CONFIG_APP_MQTT_CLIENT_ID "zb"
#define CONFIG_APP_MQTT_ROOT_TOPIC "root"
#define CONFIG_APP_MQTT_URL ""
#define CONFIG_APP_MQTT_ENABLE 0
#define CONFIG_APP_MQTT_USER ""
#define CONFIG_APP_MQTT_PASSWORD ""
#define CONFIG_STM32_HAVE_COMPONENT 1
#define CONFIG_STM32_USE_COMPONENT 1
#define CONFIG_STM32_ENABLE_RESET 1
#define CONFIG_STM32_MAKE_COMPONENT_THREAD_SAFE 1
#define CONFIG_STM32_MAKE_API_THREAD_SAFE 1
#define CONFIG_TXTIO_HAVE_COMPONENT 1
#define CONFIG_APP_UART_BAUD_RATE 115200
#define CONFIG_UOUT_PUBLISH_IP_ADDR_AS_TXT 1
#define CONFIG_REQUIRE_ROOT_OBJECT 1
#define CONFIG_APP_USE_ESP_GET_TIME 1
#define CONFIG_WEATHER_OWM_URL_STRING "http://api.openweathermap.org/data/2.5/weather?q=Berlin&APPID=12345678901234567890123456789012"
