#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := tronferno-mcu

include $(IDF_PATH)/make/project.mk

BUILD_BASE ?=../../esp32-build
BUILD_DIR_BASE ?= $(BUILD_BASE)