#ifndef COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_
#define COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_

#include "timer_state.h"

void fam_updateTimerEvent();
void fam_loop_old(void);
void fam_loop(void);

#endif /* COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_ */
