#ifndef COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_
#define COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_

#include "timer_state.h"

void fau_getnextTimerEvent();
void timer_state_loop(void);

#endif /* COMPONENTS_FERNOTRON_AUTO_INCLUDE_FERNOTRON_AUTO_TIMER_STATE_LOOP_H_ */
